
server:
  port: 9000

spring:
  profiles:
    active: dev
  # 单个文件的最大值
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/forum
#    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 60000
      connection-test-query: SELECT 1
  security:
    user:
      password: 1
      name: xbl
  banner:
    image:
      location: static/binner.png
  servlet:
    multipart:
      # 上传文件总的最大值
      max-file-size: 10MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

debug: false

